name: Build and deploy ASP.Net Core app to Azure Web App - rutvik-nytimes

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full repo is checked out

      - name: List Files in Workspace
        run: ls -R  # Debugging step to check if solution and API folder exist

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore NyTimesDotnet.sln
        working-directory: ./NyTimesDotnet  # Ensure correct path

      - name: Build with dotnet
        run: dotnet build NyTimesDotnet.sln --configuration Release --no-restore
        working-directory: ./NyTimesDotnet  # Ensure correct path

      - name: dotnet publish API Project
        run: dotnet publish NyTimes.Api/NyTimes.Api.csproj -c Release -o "${{github.workspace}}/publish"
        working-directory: ./NyTimesDotnet  # Ensure correct path

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{github.workspace}}/publish  # Correct output directory

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'rutvik-nytimes'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6D65FB10E9F84BACB05D8EE07B874731 }}
